### ISSUE TITLE
ModuleNotFoundError: No module named 'faiss'

### ISSUE THREAD

**Issue by ecumene** [chavinlo/rvc-runpod#5]
Getting something like this

```
2024-07-22T02:28:48.567516413Z The token has not been saved to the git credentials helper. Pass `add_to_git_credential=True` in this function directly or `--add-to-git-credential` if using via `huggingface-cli` if you want to set the git credential as well.
2024-07-22T02:28:48.567550868Z Token is valid (permission: fineGrained).
2024-07-22T02:28:48.567557250Z Your token has been saved to /root/.cache/huggingface/token
2024-07-22T02:28:48.567563282Z Login successful
2024-07-22T02:28:48.567569003Z Loaded as API: http://127.0.0.1:7860/ ✔
2024-07-22T02:28:48.567573972Z Loaded as API: http://127.0.0.1:7860/ ✔
2024-07-22T02:28:48.567578791Z Loaded as API: http://127.0.0.1:7860/ ✔
2024-07-22T02:28:48.567583590Z Loaded as API: http://127.0.0.1:7860/ ✔
2024-07-22T02:28:48.567588419Z Loaded as API: http://127.0.0.1:7860/ ✔
2024-07-22T02:28:48.567593228Z Loaded as API: http://127.0.0.1:7860/ ✔
2024-07-22T02:28:48.567598047Z Loaded as API: http://127.0.0.1:7860/ ✔
2024-07-22T02:28:48.567602846Z Loaded as API: http://127.0.0.1:7860/ ✔
2024-07-22T02:28:48.567607716Z Loaded as API: http://127.0.0.1:7860/ ✔
2024-07-22T02:28:48.567612575Z Loaded as API: http://127.0.0.1:7860/ ✔
2024-07-22T02:28:48.569759813Z Traceback (most recent call last):
2024-07-22T02:28:48.569782936Z   File "/rvc_serverless/main.py", line 295, in <module>
2024-07-22T02:28:48.569789138Z     main()
2024-07-22T02:28:48.569794969Z   File "/rvc_serverless/main.py", line 288, in main
2024-07-22T02:28:48.569821700Z     pipeline.prepare()
2024-07-22T02:28:48.569828753Z   File "/rvc_serverless/main.py", line 102, in prepare
2024-07-22T02:28:48.569833822Z     raise Exception("Cannot connect to gradio API")
2024-07-22T02:28:48.569838942Z Exception: Cannot connect to gradio API
2024-07-22T02:28:54.809514940Z python infer-web.py --paperspace --pycmd python
2024-07-22T02:28:56.082303869Z Traceback (most recent call last):
2024-07-22T02:28:56.082381235Z   File "/rvc_repo/infer-web.py", line 22, in <module>
2024-07-22T02:28:56.082386916Z     import faiss
2024-07-22T02:28:56.082392186Z ModuleNotFoundError: No module named 'faiss'
2024-07-22T02:28:56.360716508Z make: *** [Makefile:59: run-ui] Error 1
```

**Comment by ecumene** [comment]
Tried adding the missing libraries (faiss, config, ...) but now I'm getting this:

https://github.com/facebookresearch/fairseq/issues/5518

When removing fairseq as a dependency in the code, just to see if this is worth fixing, I got stuck on "infer_pack" not being defined.
